name = "Gruppe Adler Admin Messages";
author = "McDiod, Salbei";
logo = "logo_ca.paa";
logoOver = "logo_active_ca.paa";
tooltip = "Gruppe Adler Admin Messages";
tooltipOwned = "Gruppe Adler Admin Messages";
picture = "overview_co.paa";
actionName = "GitHub";
action = "https://github.com/gruppe-adler/grad_adminMessages";
overview = "<br/><t align='center' size='0.75'>Visit Gruppe Adler on <t href='https://gruppe-adler.de/'>our Website</t> | <t href='http://discord.gruppe-adler.de'>Discord</t> | <t href='https://www.youtube.com/user/gruppeadler'>YouTube</t> | <t href='https://twitter.com/Gruppe_Adler'>Twitter</t></t><br/><br/>This adds a message box to the escape menu. Allows players to send message to all admins and curators. You can use this to ask for tech support without ruining immersion by using global chat";
hideName = 0;
hidePicture = 0;
dlcColor[] = {0.8196, 0.5529, 0.1216, 1};
logoSmall = "logo_small_ca.paa";